### ISSUE TITLE
Manejar los tipos de datos de postgres: decimal y numeric

### ISSUE THREAD

**Issue by neowinx** [neowinx/generator-postgres-flask-restful#13]
En el generador postgres-flask-restful no se manejan los tipos de datos de  postgres: `decimal` y `numeric`, especificamente, en el proceso de mapping para tipos de SqlAlchemy, Swagger y Python

**Comment by ldbenitez** [comment]
Se agregaron los tipos decimal y numeric durante el proceso de mapeo de tipo de datos postgres. Pull Request #14
